### ISSUE TITLE
Dear herhor67

### ISSUE THREAD

**Issue by tanlucvn** [herhor67/ARXModel#1]
I really liked your herhor.net website in the draw section, but it's down now. Can you resurrect it or share the source code, or can you deploy it for free via the github page or elsewhere? I've been looking for you for quite some time...

**Comment by dawinaj** [comment]
You mean the minecraft item lore generator?
The website is currently not working due to incompetence and negligence of the domain provider.
I am doing whatever I can to bring it back up.

**Comment by tanlucvn** [comment]
Thanks, can I help you? I'm a web developer, I think I can help you in my power

**Comment by dawinaj** [comment]
Not really, there is nothing to be done other than waiting for a response from these morons in Freenom support.
Unless you mean for further development, but I treat the website as a hobby and idk if its possible to cooperate on it

**Comment by tanluc1e** [comment]
Can you share or post to your github that source code?
